// @generated by tauri-specta. Do not edit by hand.
// Regenerate: make bindings

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	saveConnectionProfile: (profile: ConnectionProfile_Deserialize) => typedError<string, string>(__TAURI_INVOKE("save_connection_profile", { profile })),
	listConnectionProfiles: () => typedError<ConnectionProfileSummary_Serialize[], string>(__TAURI_INVOKE("list_connection_profiles")),
	deleteConnectionProfile: (profileId: string) => typedError<null, string>(__TAURI_INVOKE("delete_connection_profile", { profileId })),
	testConnection: (profile: ConnectionProfile_Deserialize) => typedError<TestConnectionResult, string>(__TAURI_INVOKE("test_connection", { profile })),
	connect: (profileId: string) => typedError<ConnectionInfo, string>(__TAURI_INVOKE("connect", { profileId })),
	disconnect: (connectionId: string) => typedError<null, string>(__TAURI_INVOKE("disconnect", { connectionId })),
	listConnections: () => typedError<ConnectionInfo[], string>(__TAURI_INVOKE("list_connections")),
	executeQuery: (connectionId: string, sql: string, database: string | null, limit: number | null) => typedError<QueryResult_Serialize[], string>(__TAURI_INVOKE("execute_query", { connectionId, sql, database, limit })),
	/**
	 *  Plan a single statement.
	 * 
	 *  Separate from `execute_query` because `EXPLAIN ANALYZE` executes what it
	 *  measures: the decision to downgrade a write to a plain EXPLAIN has to sit
	 *  behind the IPC boundary, not in the caller (#412).
	 */
	explainQuery: (connectionId: string, sql: string, database: string | null, analyze: boolean) => typedError<ExplainResponse_Serialize, string>(__TAURI_INVOKE("explain_query", { connectionId, sql, database, analyze })),
	/**
	 *  Stop whatever is running on this connection.
	 * 
	 *  Issues `KILL QUERY` server-side — dropping the client future alone would
	 *  leave the statement running to completion (#420).
	 */
	cancelQuery: (connectionId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_query", { connectionId })),
	getDatabases: (connectionId: string) => typedError<DatabaseInfo[], string>(__TAURI_INVOKE("get_databases", { connectionId })),
	getTables: (connectionId: string, database: string) => typedError<TableInfo[], string>(__TAURI_INVOKE("get_tables", { connectionId, database })),
	getColumns: (connectionId: string, database: string, table: string) => typedError<ColumnInfo[], string>(__TAURI_INVOKE("get_columns", { connectionId, database, table })),
	getIndexes: (connectionId: string, database: string, table: string) => typedError<IndexInfo[], string>(__TAURI_INVOKE("get_indexes", { connectionId, database, table })),
	getTableDdl: (connectionId: string, database: string, table: string) => typedError<string, string>(__TAURI_INVOKE("get_table_ddl", { connectionId, database, table })),
	getViews: (connectionId: string, database: string) => typedError<ViewInfo[], string>(__TAURI_INVOKE("get_views", { connectionId, database })),
	getRoutines: (connectionId: string, database: string) => typedError<RoutineInfo[], string>(__TAURI_INVOKE("get_routines", { connectionId, database })),
	getTriggers: (connectionId: string, database: string) => typedError<TriggerInfo[], string>(__TAURI_INVOKE("get_triggers", { connectionId, database })),
	getViewDdl: (connectionId: string, database: string, viewName: string) => typedError<string, string>(__TAURI_INVOKE("get_view_ddl", { connectionId, database, viewName })),
	getRoutineDdl: (connectionId: string, database: string, routineName: string, routineType: string) => typedError<string, string>(__TAURI_INVOKE("get_routine_ddl", { connectionId, database, routineName, routineType })),
	getTriggerDdl: (connectionId: string, database: string, triggerName: string) => typedError<string, string>(__TAURI_INVOKE("get_trigger_ddl", { connectionId, database, triggerName })),
	exportResults: (result: QueryResult_Deserialize, format: string, tableName: string | null) => typedError<string, string>(__TAURI_INVOKE("export_results", { result, format, tableName })),
	getProcessList: (connectionId: string) => typedError<ProcessInfo[], string>(__TAURI_INVOKE("get_process_list", { connectionId })),
	getServerVariables: (connectionId: string) => typedError<ServerVariable[], string>(__TAURI_INVOKE("get_server_variables", { connectionId })),
	killProcess: (connectionId: string, processId: ProcessId) => typedError<null, string>(__TAURI_INVOKE("kill_process", { connectionId, processId })),
	readFileContents: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_file_contents", { path })),
	pickFile: (title: string, filters: ([string, string[]])[]) => typedError<string | null, string>(__TAURI_INVOKE("pick_file", { title, filters })),
	writeFileContents: (path: string, contents: string) => typedError<null, string>(__TAURI_INVOKE("write_file_contents", { path, contents })),
	pickSaveFile: (title: string, defaultName: string, filters: ([string, string[]])[]) => typedError<string | null, string>(__TAURI_INVOKE("pick_save_file", { title, defaultName, filters })),
	isRpmOstree: () => typedError<boolean, string>(__TAURI_INVOKE("is_rpm_ostree")),
	sqliteOpen: (path: string) => typedError<string, string>(__TAURI_INVOKE("sqlite_open", { path })),
	sqliteClose: (connectionId: string) => typedError<null, string>(__TAURI_INVOKE("sqlite_close", { connectionId })),
	sqliteList: () => typedError<string[], string>(__TAURI_INVOKE("sqlite_list")),
	sqliteExecute: (connectionId: string, sql: string) => typedError<SqliteQueryResult[], string>(__TAURI_INVOKE("sqlite_execute", { connectionId, sql })),
	sqliteGetTables: (connectionId: string) => typedError<SqliteTableInfo[], string>(__TAURI_INVOKE("sqlite_get_tables", { connectionId })),
	sqliteGetColumns: (connectionId: string, table: string) => typedError<SqliteColumnInfo[], string>(__TAURI_INVOKE("sqlite_get_columns", { connectionId, table })),
	sqliteGetIndexes: (connectionId: string, table: string) => typedError<SqliteIndexInfo[], string>(__TAURI_INVOKE("sqlite_get_indexes", { connectionId, table })),
	sqliteGetTableDdl: (connectionId: string, table: string) => typedError<string, string>(__TAURI_INVOKE("sqlite_get_table_ddl", { connectionId, table })),
	aiChat: (message: string, conversationId: string, mode: AiMode, connectionId: string | null, database: string | null) => typedError<string, string>(__TAURI_INVOKE("ai_chat", { message, conversationId, mode, connectionId, database })),
	aiGetStatus: () => typedError<AiStatus, string>(__TAURI_INVOKE("ai_get_status")),
	aiSetConfig: (config: AiConfig) => typedError<null, string>(__TAURI_INVOKE("ai_set_config", { config })),
	aiCancel: (conversationId: string) => typedError<null, string>(__TAURI_INVOKE("ai_cancel", { conversationId })),
	aiApprovePermission: (conversationId: string, requestId: string, approved: boolean) => typedError<null, string>(__TAURI_INVOKE("ai_approve_permission", { conversationId, requestId, approved })),
};

/* Types */
export type AiConfig = {
	model: string | null,
};

export type AiMode = "ask" | "agent" | "plan";

export type AiStatus = {
	provider: string,
	available: boolean,
	model: string | null,
};

/**  Why a requested ANALYZE was not performed. */
export type AnalyzeRefusal = 
/**  The statement writes. Running it to time it would apply the write. */
"would_mutate" | 
/**  The connection's profile is marked read-only. */
"read_only_connection";

export type ColumnInfo = {
	name: string,
	data_type: string,
	column_type: string,
	nullable: boolean,
	default_value: string | null,
	is_primary_key: boolean,
	extra: string,
	comment: string,
};

export type ColumnMeta = {
	name: string,
	data_type: string,
	nullable: boolean,
	is_primary_key: boolean,
};

export type ConnectionEnvironment = "development" | "staging" | "production";

export type ConnectionInfo = {
	id: string,
	profile_id: string,
	name: string,
	host: string,
	port: number,
	database: string | null,
	server_version: string,
	connected_at: string,
	color: string | null,
	environment: ConnectionEnvironment | null,
};

export type ConnectionProfile = ConnectionProfile_Serialize | ConnectionProfile_Deserialize;

export type ConnectionProfileSummary = ConnectionProfileSummary_Serialize | ConnectionProfileSummary_Deserialize;

export type ConnectionProfileSummary_Deserialize = {
	id: string,
	name: string,
	group: string | null,
	color: string | null,
	host: string,
	port: number,
	username: string,
	default_database: string | null,
	ssh_config: SSHConfig_Deserialize | null,
	ssl_config: SSLConfig | null,
	pool_min: number,
	pool_max: number,
	read_only: boolean,
	connect_timeout_secs: number | null,
	query_timeout_secs: number | null,
	charset: string | null,
	environment: ConnectionEnvironment | null,
	created_at: string,
	updated_at: string,
};

export type ConnectionProfileSummary_Serialize = {
	id: string,
	name: string,
	group: string | null,
	color: string | null,
	host: string,
	port: number,
	username: string,
	default_database: string | null,
	ssh_config: SSHConfig_Serialize | null,
	ssl_config: SSLConfig | null,
	pool_min: number,
	pool_max: number,
	read_only: boolean,
	connect_timeout_secs: number | null,
	query_timeout_secs: number | null,
	charset: string | null,
	environment: ConnectionEnvironment | null,
	created_at: string,
	updated_at: string,
};

export type ConnectionProfile_Deserialize = {
	id: string,
	name: string,
	group: string | null,
	color: string | null,
	host: string,
	port: number,
	username: string,
	password?: string,
	default_database: string | null,
	ssh_config: SSHConfig_Deserialize | null,
	ssl_config: SSLConfig | null,
	pool_min: number,
	pool_max: number,
	read_only: boolean,
	connect_timeout_secs: number | null,
	query_timeout_secs: number | null,
	charset: string | null,
	environment: ConnectionEnvironment | null,
	created_at: string,
	updated_at: string,
};

export type ConnectionProfile_Serialize = {
	id: string,
	name: string,
	group: string | null,
	color: string | null,
	host: string,
	port: number,
	username: string,
	default_database: string | null,
	ssh_config: SSHConfig_Serialize | null,
	ssl_config: SSLConfig | null,
	pool_min: number,
	pool_max: number,
	read_only: boolean,
	connect_timeout_secs: number | null,
	query_timeout_secs: number | null,
	charset: string | null,
	environment: ConnectionEnvironment | null,
	created_at: string,
	updated_at: string,
};

export type DatabaseInfo = {
	name: string,
	default_charset: string,
	default_collation: string,
};

export type ExplainResponse = ExplainResponse_Serialize | ExplainResponse_Deserialize;

export type ExplainResponse_Deserialize = {
	result: QueryResult_Deserialize,
	/**  True when the output is ANALYZE-shaped (actual timings), false for a plan. */
	analyzed: boolean,
	/**
	 *  Set when ANALYZE was asked for and deliberately not run. The caller shows
	 *  this to the user; `result` holds the plain EXPLAIN performed instead.
	 */
	refusal: AnalyzeRefusal | null,
	/**
	 *  True when the plan came back in MariaDB's tabular ANALYZE shape rather
	 *  than MySQL's single-column TREE text (#422).
	 */
	tabular: boolean,
};

export type ExplainResponse_Serialize = {
	result: QueryResult_Serialize,
	/**  True when the output is ANALYZE-shaped (actual timings), false for a plan. */
	analyzed: boolean,
	/**
	 *  Set when ANALYZE was asked for and deliberately not run. The caller shows
	 *  this to the user; `result` holds the plain EXPLAIN performed instead.
	 */
	refusal: AnalyzeRefusal | null,
	/**
	 *  True when the plan came back in MariaDB's tabular ANALYZE shape rather
	 *  than MySQL's single-column TREE text (#422).
	 */
	tabular: boolean,
};

export type IndexInfo = {
	name: string,
	columns: string[],
	is_unique: boolean,
	index_type: string,
};

/**
 *  A MySQL process id.
 * 
 *  A newtype purely so the TypeScript side gets a plain `number`: command
 *  arguments cannot carry `#[specta(type = ...)]`, and a bare `f64` argument
 *  would be exported as `number | null`, letting the frontend pass a null that
 *  Rust then rejects at runtime. `#[serde(transparent)]` keeps the wire format
 *  identical to the bare integer.
 */
export type ProcessId = number;

export type ProcessInfo = {
	id: number,
	user: string,
	host: string,
	db: string | null,
	command: string,
	time: number,
	state: string | null,
	info: string | null,
};

export type QueryResult = QueryResult_Serialize | QueryResult_Deserialize;

export type QueryResult_Deserialize = {
	query_id: string,
	statement_index: number,
	columns: ColumnMeta[],
	rows: SqlValue[][],
	rows_affected: number,
	execution_time_ms: number,
	warnings: string[],
	rows_truncated: boolean,
	total_rows_available: number | null,
};

export type QueryResult_Serialize = {
	query_id: string,
	statement_index: number,
	columns: ColumnMeta[],
	rows: SqlValue[][],
	rows_affected: number,
	execution_time_ms: number,
	warnings: string[],
	rows_truncated: boolean,
	total_rows_available?: number | null,
};

export type RoutineInfo = {
	name: string,
	routine_type: string,
	data_type: string,
};

export type SSHConfig = SSHConfig_Serialize | SSHConfig_Deserialize;

export type SSHConfig_Deserialize = {
	host: string,
	port: number,
	username: string,
	password?: string | null,
	private_key_path: string | null,
	passphrase?: string | null,
};

export type SSHConfig_Serialize = {
	host: string,
	port: number,
	username: string,
	private_key_path: string | null,
};

export type SSLConfig = {
	mode: SSLMode,
	ca_cert_path: string | null,
	client_cert_path: string | null,
	client_key_path: string | null,
};

export type SSLMode = "Disabled" | "Preferred" | "Required" | "VerifyCA" | "VerifyIdentity";

export type ServerVariable = {
	name: string,
	value: string,
};

export type SqlValue = "Null" | boolean | number | number | null | string | number[];

export type SqliteColumnInfo = {
	name: string,
	data_type: string,
	nullable: boolean,
	default_value: string | null,
	is_primary_key: boolean,
};

export type SqliteColumnMeta = {
	name: string,
	data_type: string,
	nullable: boolean,
	is_primary_key: boolean,
};

export type SqliteIndexInfo = {
	name: string,
	columns: string[],
	is_unique: boolean,
};

export type SqliteQueryResult = {
	query_id: string,
	statement_index: number,
	columns: SqliteColumnMeta[],
	rows: unknown[][],
	rows_affected: number,
	execution_time_ms: number,
	warnings: string[],
	rows_truncated: boolean,
};

export type SqliteTableInfo = {
	name: string,
	table_type: string,
	row_count: number | null,
	sql: string | null,
};

export type TableInfo = {
	name: string,
	table_type: string,
	engine: string | null,
	row_count: number | null,
	data_size: number | null,
	comment: string,
};

export type TestConnectionResult = {
	success: boolean,
	message: string,
	server_version: string | null,
	latency_ms: number,
};

export type TriggerInfo = {
	name: string,
	event: string,
	table: string,
	timing: string,
};

export type ViewInfo = {
	name: string,
	is_updatable: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

