// @generated by tauri-specta. Do not edit by hand.
// Regenerate: make bindings

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	saveConnectionProfile: (profile: ConnectionProfile_Deserialize) => typedError<string, string>(__TAURI_INVOKE("save_connection_profile", { profile })),
	listConnectionProfiles: () => typedError<ConnectionProfileSummary_Serialize[], string>(__TAURI_INVOKE("list_connection_profiles")),
	deleteConnectionProfile: (profileId: string) => typedError<null, string>(__TAURI_INVOKE("delete_connection_profile", { profileId })),
	testConnection: (profile: ConnectionProfile_Deserialize) => typedError<TestConnectionResult, string>(__TAURI_INVOKE("test_connection", { profile })),
	connect: (profileId: string) => typedError<ConnectionInfo, string>(__TAURI_INVOKE("connect", { profileId })),
	disconnect: (connectionId: string) => typedError<null, string>(__TAURI_INVOKE("disconnect", { connectionId })),
	listConnections: () => typedError<ConnectionInfo[], string>(__TAURI_INVOKE("list_connections")),
	executeQuery: (connectionId: string, sql: string, database: string | null, limit: number | null) => typedError<QueryResult_Serialize[], QueryError>(__TAURI_INVOKE("execute_query", { connectionId, sql, database, limit })),
	/**
	 *  Plan a single statement.
	 * 
	 *  Separate from `execute_query` because `EXPLAIN ANALYZE` executes what it
	 *  measures: the decision to downgrade a write to a plain EXPLAIN has to sit
	 *  behind the IPC boundary, not in the caller (#412).
	 */
	explainQuery: (connectionId: string, sql: string, database: string | null, analyze: boolean) => typedError<ExplainResponse_Serialize, string>(__TAURI_INVOKE("explain_query", { connectionId, sql, database, analyze })),
	/**
	 *  Stop whatever is running on this connection.
	 * 
	 *  Issues `KILL QUERY` server-side — dropping the client future alone would
	 *  leave the statement running to completion (#420).
	 */
	cancelQuery: (connectionId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_query", { connectionId })),
	getDatabases: (connectionId: string) => typedError<DatabaseInfo[], string>(__TAURI_INVOKE("get_databases", { connectionId })),
	getTables: (connectionId: string, database: string) => typedError<TableInfo[], string>(__TAURI_INVOKE("get_tables", { connectionId, database })),
	getColumns: (connectionId: string, database: string, table: string) => typedError<ColumnInfo[], string>(__TAURI_INVOKE("get_columns", { connectionId, database, table })),
	getIndexes: (connectionId: string, database: string, table: string) => typedError<IndexInfo[], string>(__TAURI_INVOKE("get_indexes", { connectionId, database, table })),
	getForeignKeys: (connectionId: string, database: string, table: string) => typedError<ForeignKeyInfo[], string>(__TAURI_INVOKE("get_foreign_keys", { connectionId, database, table })),
	getTableDdl: (connectionId: string, database: string, table: string) => typedError<string, string>(__TAURI_INVOKE("get_table_ddl", { connectionId, database, table })),
	getViews: (connectionId: string, database: string) => typedError<ViewInfo[], string>(__TAURI_INVOKE("get_views", { connectionId, database })),
	getRoutines: (connectionId: string, database: string) => typedError<RoutineInfo[], string>(__TAURI_INVOKE("get_routines", { connectionId, database })),
	getTriggers: (connectionId: string, database: string) => typedError<TriggerInfo[], string>(__TAURI_INVOKE("get_triggers", { connectionId, database })),
	getViewDdl: (connectionId: string, database: string, viewName: string) => typedError<string, string>(__TAURI_INVOKE("get_view_ddl", { connectionId, database, viewName })),
	getRoutineDdl: (connectionId: string, database: string, routineName: string, routineType: string) => typedError<string, string>(__TAURI_INVOKE("get_routine_ddl", { connectionId, database, routineName, routineType })),
	getTriggerDdl: (connectionId: string, database: string, triggerName: string) => typedError<string, string>(__TAURI_INVOKE("get_trigger_ddl", { connectionId, database, triggerName })),
	exportResults: (result: QueryResult_Deserialize, format: string, tableName: string | null) => typedError<string, string>(__TAURI_INVOKE("export_results", { result, format, tableName })),
	getProcessList: (connectionId: string) => typedError<ProcessInfo[], string>(__TAURI_INVOKE("get_process_list", { connectionId })),
	getServerVariables: (connectionId: string) => typedError<ServerVariable[], string>(__TAURI_INVOKE("get_server_variables", { connectionId })),
	killProcess: (connectionId: string, processId: ProcessId) => typedError<null, string>(__TAURI_INVOKE("kill_process", { connectionId, processId })),
	/**
	 *  Abort the statement a session is running, without dropping the session.
	 * 
	 *  The proportionate response to a long-running query: `kill_process` drops
	 *  the whole connection and its transaction with it (#430).
	 */
	killQuery: (connectionId: string, processId: ProcessId) => typedError<null, string>(__TAURI_INVOKE("kill_query", { connectionId, processId })),
	/**
	 *  Server thread ids belonging to SQLPilot's own pool for this connection.
	 * 
	 *  The process list shows every session on the server, including the ones the
	 *  app is using to read that very list. The UI needs to tell them apart so it
	 *  can present its own as un-killable rather than letting the user disconnect
	 *  the app from the server it is managing (#433).
	 */
	getOwnThreadIds: (connectionId: string) => typedError<ProcessId[], string>(__TAURI_INVOKE("get_own_thread_ids", { connectionId })),
	readFileContents: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_file_contents", { path })),
	pickFile: (title: string, filters: ([string, string[]])[]) => typedError<string | null, string>(__TAURI_INVOKE("pick_file", { title, filters })),
	writeFileContents: (path: string, contents: string) => typedError<null, string>(__TAURI_INVOKE("write_file_contents", { path, contents })),
	pickSaveFile: (title: string, defaultName: string, filters: ([string, string[]])[]) => typedError<string | null, string>(__TAURI_INVOKE("pick_save_file", { title, defaultName, filters })),
	getPlatformInfo: () => typedError<PlatformInfo, string>(__TAURI_INVOKE("get_platform_info")),
	/**  Record one executed statement, then trim to `limit`. */
	historyAdd: (entry: HistoryEntry, limit: number) => typedError<HistoryEntry, string>(__TAURI_INVOKE("history_add", { entry, limit })),
	historyList: (query: HistoryQuery) => typedError<HistoryEntry[], string>(__TAURI_INVOKE("history_list", { query })),
	historyRemove: (id: string) => typedError<null, string>(__TAURI_INVOKE("history_remove", { id })),
	historyClear: () => typedError<null, string>(__TAURI_INVOKE("history_clear")),
	historyCount: () => typedError<number, string>(__TAURI_INVOKE("history_count")),
	/**  Apply a lowered retention limit straight away. */
	historyPrune: (limit: number) => typedError<number, string>(__TAURI_INVOKE("history_prune", { limit })),
	/**
	 *  Take over a history that was still in localStorage. Ids carry across, so
	 *  running this twice imports nothing the second time.
	 */
	historyImport: (entries: HistoryEntry[], limit: number) => typedError<number, string>(__TAURI_INVOKE("history_import", { entries, limit })),
	/**  How many entries the same filter matches, ignoring its page size. */
	historyCountMatching: (query: HistoryQuery) => typedError<number, string>(__TAURI_INVOKE("history_count_matching", { query })),
	/**  The connections and databases that appear in the history, for the filters. */
	historyFacets: () => typedError<HistoryFacets, string>(__TAURI_INVOKE("history_facets")),
	/**  Render everything the filter matches, not only the page on screen. */
	historyExport: (query: HistoryQuery, format: HistoryExportFormat) => typedError<string, string>(__TAURI_INVOKE("history_export", { query, format })),
	/**  Whether connection passwords can be stored between sessions. */
	keyringAvailable: () => __TAURI_INVOKE<boolean>("keyring_available"),
	sqliteOpen: (path: string) => typedError<string, string>(__TAURI_INVOKE("sqlite_open", { path })),
	sqliteClose: (connectionId: string) => typedError<null, string>(__TAURI_INVOKE("sqlite_close", { connectionId })),
	sqliteList: () => typedError<string[], string>(__TAURI_INVOKE("sqlite_list")),
	sqliteExecute: (connectionId: string, sql: string) => typedError<SqliteQueryResult[], QueryError>(__TAURI_INVOKE("sqlite_execute", { connectionId, sql })),
	sqliteGetTables: (connectionId: string) => typedError<SqliteTableInfo[], string>(__TAURI_INVOKE("sqlite_get_tables", { connectionId })),
	sqliteGetColumns: (connectionId: string, table: string) => typedError<SqliteColumnInfo[], string>(__TAURI_INVOKE("sqlite_get_columns", { connectionId, table })),
	sqliteGetIndexes: (connectionId: string, table: string) => typedError<SqliteIndexInfo[], string>(__TAURI_INVOKE("sqlite_get_indexes", { connectionId, table })),
	sqliteGetTableDdl: (connectionId: string, table: string) => typedError<string, string>(__TAURI_INVOKE("sqlite_get_table_ddl", { connectionId, table })),
	aiChat: (message: string, conversationId: string, mode: AiMode, connectionId: string | null, database: string | null) => typedError<string, string>(__TAURI_INVOKE("ai_chat", { message, conversationId, mode, connectionId, database })),
	aiGetStatus: () => typedError<AiStatus, string>(__TAURI_INVOKE("ai_get_status")),
	aiSetConfig: (config: AiConfig) => typedError<null, string>(__TAURI_INVOKE("ai_set_config", { config })),
	aiCancel: (conversationId: string) => typedError<null, string>(__TAURI_INVOKE("ai_cancel", { conversationId })),
	aiApprovePermission: (conversationId: string, requestId: string, approved: boolean) => typedError<null, string>(__TAURI_INVOKE("ai_approve_permission", { conversationId, requestId, approved })),
};

/* Types */
export type AiConfig = {
	model: string | null,
};

export type AiMode = "ask" | "agent" | "plan";

export type AiStatus = {
	provider: string,
	available: boolean,
	model: string | null,
};

/**  Why a requested ANALYZE was not performed. */
export type AnalyzeRefusal = 
/**  The statement writes. Running it to time it would apply the write. */
"would_mutate" | 
/**  The connection's profile is marked read-only. */
"read_only_connection";

export type ColumnInfo = {
	name: string,
	data_type: string,
	column_type: string,
	nullable: boolean,
	default_value: string | null,
	is_primary_key: boolean,
	extra: string,
	comment: string,
	/**
	 *  Only set for string columns, and only when the column carries its own
	 *  character set rather than inheriting the table's. COLUMN_TYPE does not
	 *  include either, so without these a round-trip through the designer
	 *  would rewrite the column with the table default (#377).
	 */
	charset: string | null,
	collation: string | null,
};

export type ColumnMeta = {
	name: string,
	data_type: string,
	nullable: boolean,
	is_primary_key: boolean,
};

export type ConnectionEnvironment = "development" | "staging" | "production";

export type ConnectionInfo = {
	id: string,
	profile_id: string,
	name: string,
	host: string,
	port: number,
	database: string | null,
	server_version: string,
	connected_at: string,
	color: string | null,
	environment: ConnectionEnvironment | null,
};

export type ConnectionProfile = ConnectionProfile_Serialize | ConnectionProfile_Deserialize;

export type ConnectionProfileSummary = ConnectionProfileSummary_Serialize | ConnectionProfileSummary_Deserialize;

export type ConnectionProfileSummary_Deserialize = {
	id: string,
	name: string,
	group: string | null,
	color: string | null,
	host: string,
	port: number,
	username: string,
	default_database: string | null,
	ssh_config: SSHConfig_Deserialize | null,
	ssl_config: SSLConfig | null,
	pool_min: number,
	pool_max: number,
	read_only: boolean,
	connect_timeout_secs: number | null,
	query_timeout_secs: number | null,
	charset: string | null,
	environment: ConnectionEnvironment | null,
	created_at: string,
	updated_at: string,
};

export type ConnectionProfileSummary_Serialize = {
	id: string,
	name: string,
	group: string | null,
	color: string | null,
	host: string,
	port: number,
	username: string,
	default_database: string | null,
	ssh_config: SSHConfig_Serialize | null,
	ssl_config: SSLConfig | null,
	pool_min: number,
	pool_max: number,
	read_only: boolean,
	connect_timeout_secs: number | null,
	query_timeout_secs: number | null,
	charset: string | null,
	environment: ConnectionEnvironment | null,
	created_at: string,
	updated_at: string,
};

export type ConnectionProfile_Deserialize = {
	id: string,
	name: string,
	group: string | null,
	color: string | null,
	host: string,
	port: number,
	username: string,
	password?: string,
	default_database: string | null,
	ssh_config: SSHConfig_Deserialize | null,
	ssl_config: SSLConfig | null,
	pool_min: number,
	pool_max: number,
	read_only: boolean,
	connect_timeout_secs: number | null,
	query_timeout_secs: number | null,
	charset: string | null,
	environment: ConnectionEnvironment | null,
	created_at: string,
	updated_at: string,
};

export type ConnectionProfile_Serialize = {
	id: string,
	name: string,
	group: string | null,
	color: string | null,
	host: string,
	port: number,
	username: string,
	default_database: string | null,
	ssh_config: SSHConfig_Serialize | null,
	ssl_config: SSLConfig | null,
	pool_min: number,
	pool_max: number,
	read_only: boolean,
	connect_timeout_secs: number | null,
	query_timeout_secs: number | null,
	charset: string | null,
	environment: ConnectionEnvironment | null,
	created_at: string,
	updated_at: string,
};

export type DatabaseInfo = {
	name: string,
	default_charset: string,
	default_collation: string,
};

export type ExplainResponse = ExplainResponse_Serialize | ExplainResponse_Deserialize;

export type ExplainResponse_Deserialize = {
	result: QueryResult_Deserialize,
	/**  True when the output is ANALYZE-shaped (actual timings), false for a plan. */
	analyzed: boolean,
	/**
	 *  Set when ANALYZE was asked for and deliberately not run. The caller shows
	 *  this to the user; `result` holds the plain EXPLAIN performed instead.
	 */
	refusal: AnalyzeRefusal | null,
	/**
	 *  True when the plan came back in MariaDB's tabular ANALYZE shape rather
	 *  than MySQL's single-column TREE text (#422).
	 */
	tabular: boolean,
};

export type ExplainResponse_Serialize = {
	result: QueryResult_Serialize,
	/**  True when the output is ANALYZE-shaped (actual timings), false for a plan. */
	analyzed: boolean,
	/**
	 *  Set when ANALYZE was asked for and deliberately not run. The caller shows
	 *  this to the user; `result` holds the plain EXPLAIN performed instead.
	 */
	refusal: AnalyzeRefusal | null,
	/**
	 *  True when the plan came back in MariaDB's tabular ANALYZE shape rather
	 *  than MySQL's single-column TREE text (#422).
	 */
	tabular: boolean,
};

export type ForeignKeyInfo = {
	name: string,
	/**
	 *  In key order. A composite foreign key spans several rows of
	 *  KEY_COLUMN_USAGE, which ORDINAL_POSITION puts back in order.
	 */
	columns: string[],
	referenced_table: string,
	referenced_columns: string[],
	on_update: string,
	on_delete: string,
};

export type HistoryEntry = {
	id: string,
	sql: string,
	connectionName: string,
	database: string | null,
	/**  ISO 8601, UTC. */
	executedAt: string,
	executionTimeMs: number,
	rowCount: number,
	/**  "success" or "error". */
	status: string,
	error: string | null,
	/**  Driver error number — MySQL's code, SQLite's extended result code. */
	errorCode: number | null,
	errorSqlState: string | null,
	/**  A credential was stripped before this was stored (#587). */
	redacted: boolean,
	/**  The statement was longer than [`MAX_SQL_BYTES`] and is stored cut. */
	truncated: boolean,
};

/**  What an export is written as. */
export type HistoryExportFormat = 
/**  Every column, for a spreadsheet. */
"csv" | 
/**
 *  The statements alone, each with a comment carrying its context, so the
 *  file can be read back by any SQL client — including this one.
 */
"sql";

/**
 *  The distinct values a filter can offer, read from what is actually stored.
 * 
 *  Offering every connection the user has ever configured would list ones with
 *  no history; offering these lists only what filtering by would return
 *  something.
 */
export type HistoryFacets = {
	connectionNames: string[],
	databases: string[],
};

/**
 *  What to return from [`HistoryStore::list`].
 * 
 *  Everything recorded on an entry used to be unusable for finding it: the
 *  panel matched a substring of the SQL and nothing else, so "what did I run
 *  against staging yesterday that failed" and "what were my slowest queries"
 *  were both unanswerable (#589). Filtering is a WHERE clause rather than an
 *  array scan, which is the other half of why history moved to SQLite.
 */
export type HistoryQuery = {
	/**  Substring match over the SQL text. Case-insensitive. */
	search: string | null,
	/**  Keep only these connections. Empty or absent means all of them. */
	connectionNames: string[] | null,
	/**  Keep only these databases. */
	databases: string[] | null,
	/**  "success" or "error". Absent means both. */
	status: string | null,
	/**  ISO 8601, inclusive. Compared as text, which sorts chronologically. */
	executedAfter: string | null,
	executedBefore: string | null,
	/**  Keep only entries at least this slow, in milliseconds. */
	minDurationMs: number | null,
	sort: HistorySort | null,
	/**  Page size. Absent means every match — which is what an export wants. */
	limit: number | null,
	offset: number | null,
};

/**  How to sort a history listing. */
export type HistorySort = 
/**  Newest first. What the panel shows unless asked otherwise. */
"recent" | 
/**  Slowest first — the "what is costing me time" view. */
"slowest" | 
/**  Largest result first. */
"most_rows";

export type IndexInfo = {
	name: string,
	columns: string[],
	is_unique: boolean,
	index_type: string,
};

/**
 *  How this copy of SQLPilot was installed, which decides whether it may
 *  update itself.
 * 
 *  The previous check was `Path::new("/usr/bin/rpm-ostree").exists()`, which
 *  answers a narrower question than the one being asked and gets the
 *  important case backwards. Inside a Flatpak sandbox the host's `/usr` is
 *  not visible, so a Flatpak on Silverblue sees no rpm-ostree binary, reports
 *  itself as an ordinary install, and is offered an auto-update its runtime
 *  cannot apply (#354).
 */
export type PackageFormat = 
/**  A plain install that owns its own files, and can replace them. */
"standard" | 
/**  Tauri's updater handles this format directly. */
"app_image" | 
/**  The runtime owns updates; the app must not replace its own files. */
"flatpak" | 
/**  As Flatpak — snapd manages the revision. */
"snap" | 
/**
 *  An OSTree-booted system: /usr is immutable and layered packages are
 *  applied by rpm-ostree, taking effect on the next boot.
 */
"rpm_ostree";

export type PlatformInfo = {
	package_format: PackageFormat,
	/**
	 *  `x86_64`, `aarch64`. Needed to name the right download in a manual
	 *  update command (#571).
	 */
	arch: string,
};

/**
 *  A MySQL process id.
 * 
 *  A newtype purely so the TypeScript side gets a plain `number`: command
 *  arguments cannot carry `#[specta(type = ...)]`, and a bare `f64` argument
 *  would be exported as `number | null`, letting the frontend pass a null that
 *  Rust then rejects at runtime. `#[serde(transparent)]` keeps the wire format
 *  identical to the bare integer.
 */
export type ProcessId = number;

export type ProcessInfo = {
	id: number,
	user: string,
	host: string,
	db: string | null,
	command: string,
	time: number,
	state: string | null,
	info: string | null,
};

/**
 *  A query failure in the shape the frontend can act on.
 * 
 *  Commands hand the frontend `Result<_, String>`, which is enough to show a
 *  message and nothing else: the history panel could not tell a missing table
 *  from a syntax error, and a user debugging a recurring failure had to rerun
 *  the query to find out which table was missing (#324).
 * 
 *  The driver already knows more than the message says. MySQL reports an error
 *  number (1146 for an unknown table) and a SQLSTATE (42S02); SQLite reports an
 *  extended result code. Both are stable identifiers worth keeping, so this
 *  carries them alongside the text rather than flattening everything to one
 *  string at the boundary.
 */
export type QueryError = {
	/**  The message the user reads. Always present. */
	message: string,
	/**
	 *  Driver error number: MySQL's error code, or SQLite's extended result
	 *  code. `None` for failures that never reached a server.
	 */
	code: number | null,
	/**  SQLSTATE, where the driver supplies one. MySQL does; SQLite does not. */
	sqlState: string | null,
};

export type QueryResult = QueryResult_Serialize | QueryResult_Deserialize;

export type QueryResult_Deserialize = {
	query_id: string,
	statement_index: number,
	columns: ColumnMeta[],
	rows: SqlValue[][],
	rows_affected: number,
	execution_time_ms: number,
	warnings: string[],
	/**
	 *  Whether rows were withheld. Derived from `truncation_reason` at the one
	 *  place a truncated result is built, so the two cannot disagree.
	 */
	rows_truncated: boolean,
	/**
	 *  Why rows were withheld, when they were. The banner needs this: telling
	 *  someone to add a LIMIT is wrong advice when the cap was memory, and
	 *  they will respond by raising a LIMIT that was never the constraint.
	 */
	truncation_reason: TruncationReason | null,
	total_rows_available: number | null,
};

export type QueryResult_Serialize = {
	query_id: string,
	statement_index: number,
	columns: ColumnMeta[],
	rows: SqlValue[][],
	rows_affected: number,
	execution_time_ms: number,
	warnings: string[],
	/**
	 *  Whether rows were withheld. Derived from `truncation_reason` at the one
	 *  place a truncated result is built, so the two cannot disagree.
	 */
	rows_truncated: boolean,
	/**
	 *  Why rows were withheld, when they were. The banner needs this: telling
	 *  someone to add a LIMIT is wrong advice when the cap was memory, and
	 *  they will respond by raising a LIMIT that was never the constraint.
	 */
	truncation_reason?: TruncationReason | null,
	total_rows_available?: number | null,
};

export type RoutineInfo = {
	name: string,
	routine_type: string,
	data_type: string,
};

export type SSHConfig = SSHConfig_Serialize | SSHConfig_Deserialize;

export type SSHConfig_Deserialize = {
	host: string,
	port: number,
	username: string,
	password?: string | null,
	private_key_path: string | null,
	passphrase?: string | null,
};

export type SSHConfig_Serialize = {
	host: string,
	port: number,
	username: string,
	private_key_path: string | null,
};

export type SSLConfig = {
	mode: SSLMode,
	ca_cert_path: string | null,
	client_cert_path: string | null,
	client_key_path: string | null,
};

export type SSLMode = "Disabled" | "Preferred" | "Required" | "VerifyCA" | "VerifyIdentity";

export type ServerVariable = {
	name: string,
	value: string,
};

export type SqlValue = "Null" | boolean | number | number | null | string | number[];

export type SqliteColumnInfo = {
	name: string,
	data_type: string,
	nullable: boolean,
	default_value: string | null,
	is_primary_key: boolean,
};

export type SqliteColumnMeta = {
	name: string,
	data_type: string,
	nullable: boolean,
	is_primary_key: boolean,
};

export type SqliteIndexInfo = {
	name: string,
	columns: string[],
	is_unique: boolean,
};

export type SqliteQueryResult = {
	query_id: string,
	statement_index: number,
	columns: SqliteColumnMeta[],
	rows: unknown[][],
	rows_affected: number,
	execution_time_ms: number,
	warnings: string[],
	rows_truncated: boolean,
};

export type SqliteTableInfo = {
	name: string,
	table_type: string,
	row_count: number | null,
	sql: string | null,
};

export type TableInfo = {
	name: string,
	table_type: string,
	engine: string | null,
	row_count: number | null,
	data_size: number | null,
	comment: string,
};

export type TestConnectionResult = {
	success: boolean,
	message: string,
	server_version: string | null,
	latency_ms: number,
};

export type TriggerInfo = {
	name: string,
	event: string,
	table: string,
	timing: string,
};

/**  What stopped the result set from being complete. */
export type TruncationReason = 
/**
 *  The caller's row limit was reached. Asking for fewer rows, or raising
 *  the limit, is a meaningful response.
 */
"row_limit" | 
/**
 *  Available system memory fell below the guard's floor mid-fetch, so the
 *  fetch stopped early. A larger LIMIT cannot help; a narrower projection
 *  or a WHERE clause can.
 */
"memory_guard";

export type ViewInfo = {
	name: string,
	is_updatable: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

