//! Generates `src/lib/bindings.ts` from the Rust command definitions.
//!
//! Run with `cargo test -p sqlpilot --features beta-ai export_bindings`, or
//! `make bindings`. The beta-ai feature matters: without it the AI commands
//! are absent from the builder and would be dropped from the output, so the
//! generated file is always produced with every command present.
//!
//! CI runs this and fails if the checked-in file differs, which is what stops
//! the TypeScript drifting from the Rust.
//!
//! Gated on the feature so a plain `cargo test` cannot regenerate a partial
//! file: without beta-ai the AI commands are absent from the builder.

// Only compiled with beta-ai on. Without the feature the AI commands are not
// in the builder, so running this would quietly rewrite bindings.ts without
// them — which a plain `cargo test` did, until this gate.
#[cfg(feature = "beta-ai")]
#[test]
fn export_bindings() {
    let header = "// @generated by tauri-specta. Do not edit by hand.\n\
                  // Regenerate: make bindings\n";

    sqlpilot_lib::specta_builder()
        .export(
            specta_typescript::Typescript::default().header(header),
            "../src/lib/bindings.ts",
        )
        .expect("failed to export TypeScript bindings");
}
