//! Generates `src/lib/bindings.ts` from the Rust command definitions.
//!
//! Run with `cargo test -p sqlpilot export_bindings`, or `just bindings`.
//!
//! CI runs this and fails if the checked-in file differs, which is what stops
//! the TypeScript drifting from the Rust.
//!
//! This used to be gated on the `beta-ai` feature, because without it the AI
//! commands were absent from the builder and a plain `cargo test` would
//! quietly rewrite the file without them. ADR-011 removed the feature, so
//! there is one command list again and no way to generate a partial file.

#[test]
fn export_bindings() {
    let header = "// @generated by tauri-specta. Do not edit by hand.\n\
                  // Regenerate: just bindings\n";

    sqlpilot_lib::specta_builder()
        .export(
            specta_typescript::Typescript::default().header(header),
            "../src/lib/bindings.ts",
        )
        .expect("failed to export TypeScript bindings");
}
